first = input ("Enter first number: ")
first = float(first)
second = input ("Enter second number: ")
second = float(second)
print (first, '+', second, '=', first + second)
print (first, '-', second, '=', first - second)
print (first, '*', second, '=', first * second)
print (first, '/', second, '=', first / second) 
print ("/n end of the program")